
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	[general.types]

		[general.types.leaves_type]

			[general.types.leaves_type.biomesoplenty]
				origin = true
				flowering_oak = true
				maple = true
				orange_autumn = true
				yellow_autumn = true
				rainbow_birch = true
				snowblossom = true
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.leaves_type.blue_skies]
				crystallized = true
				crescent_fruit = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.leaves_type.twilightforest]
				beanstalk = true
				thorn = true
				twilight_oak = true
				canopy = true
				mangrove = true
				dark = true
				rainbow_oak = true
				time = true
				transformation = true
				mining = true
				sorting = true

			[general.types.leaves_type.eldritch_end]
				primordial = true

			[general.types.leaves_type.betterend]
				pythadendron = true
				lacugrove = true
				dragon_tree = true
				tenanea = true
				lucernia = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.deep_aether]
				roseroot = true
				flowering_roseroot = true
				blue_roseroot = true
				flowering_blue_roseroot = true
				yagroot = true
				cruderoot = true
				conberry = true
				sunroot = true

			[general.types.leaves_type.aether_redux]
				blightwillow = true
				glacia = true
				gilded_oak = true
				blighted_skyroot = true
				chromatic = true
				chromatic_berry = true

			[general.types.leaves_type.chipped]
				apple_acacia = true
				cherry_acacia = true
				dead_acacia = true
				frosted_acacia = true
				golden_acacia = true
				golden_apple_acacia = true
				golden_cherry_acacia = true
				magenta_flower_acacia = true
				orange_acacia = true
				red_acacia = true
				white_flower_acacia = true
				apple_birch = true
				cherry_birch = true
				dead_birch = true
				frosted_birch = true
				golden_birch = true
				golden_apple_birch = true
				golden_cherry_birch = true
				magenta_flower_birch = true
				orange_birch = true
				red_birch = true
				white_flower_birch = true
				apple_dark_oak = true
				cherry_dark_oak = true
				dead_dark_oak = true
				frosted_dark_oak = true
				golden_dark_oak = true
				golden_apple_dark_oak = true
				golden_cherry_dark_oak = true
				magenta_flower_dark_oak = true
				orange_dark_oak = true
				red_dark_oak = true
				white_flower_dark_oak = true
				apple_jungle = true
				cherry_jungle = true
				dead_jungle = true
				frosted_jungle = true
				golden_jungle = true
				golden_apple_jungle = true
				golden_cherry_jungle = true
				magenta_flower_jungle = true
				orange_jungle = true
				red_jungle = true
				white_flower_jungle = true
				apple_oak = true
				cherry_oak = true
				dead_oak = true
				frosted_oak = true
				golden_oak = true
				golden_apple_oak = true
				golden_cherry_oak = true
				magenta_flower_oak = true
				orange_oak = true
				red_oak = true
				white_flower_oak = true
				apple_spruce = true
				cherry_spruce = true
				dead_spruce = true
				frosted_spruce = true
				golden_spruce = true
				golden_apple_spruce = true
				golden_cherry_spruce = true
				magenta_flower_spruce = true
				orange_spruce = true
				red_spruce = true
				white_flower_spruce = true

			[general.types.leaves_type.twilightdelight]
				ironwood = true

			[general.types.leaves_type.deeperdarker]
				echo = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.endlessbiomes]
				penumbral = true
				glowing_penumbral = true

		[general.types.cake]

			[general.types.cake.blue_skies]
				comet_berry_pie = true

		[general.types.wood_type]

			[general.types.wood_type.blue_skies]
				crystallized = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.wood_type.gardens_of_the_dead]
				soulblight = true
				whistlecane = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.eldritch_end]
				primordial = true

			[general.types.wood_type.betterend]
				mossy_glowshroom = true
				pythadendron = true
				end_lotus = true
				lacugrove = true
				dragon_tree = true
				tenanea = true
				helix_tree = true
				umbrella_tree = true
				jellyshroom = true
				lucernia = true

			[general.types.wood_type.biomesoplenty]
				fir = true
				redwood = true
				mahogany = true
				jacaranda = true
				palm = true
				willow = true
				dead = true
				magic = true
				umbran = true
				hellbark = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.deep_aether]
				roseroot = true
				yagroot = true
				cruderoot = true
				conberry = true
				sunroot = true

			[general.types.wood_type.aether_redux]
				fieldsprout = true
				blightwillow = true
				cloudcap = true
				springshroom = true
				crystal = true
				glacia = true

			[general.types.wood_type.twilightforest]
				twilight_oak = true
				canopy = true
				mangrove = true
				dark = true
				time = true
				transformation = true
				mining = true
				sorting = true

			[general.types.wood_type.deeperdarker]
				echo = true

			[general.types.wood_type.endlessbiomes]
				penumbra = true
				twisted = true

	[general.entries]

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

		[general.entries.wood_type]

			[general.entries.wood_type.chipped]
				fine_planks = true
				checkered_trapdoor = true
				overgrown_trapdoor = true
				overgrown_door = true
				windowed_door = true
				tiled_door = true
				classic_trapdoor = true
				circle_glass = true
				pegged_planks = true
				torch = true
				secret_door = true
				smooth_planks = true
				screen_door = true
				bared_glass = true
				ornate_bared_glass = true
				hewn_planks = true
				crossed_planks = true
				beach_door = true
				fine_vertical_planks = true
				cross_laced_planks = true
				diamond_bordered_glass = true
				railed_planks = true
				planks_mosaic = true
				distorted_trapdoor = true
				iron_barred_trapdoor = true
				circle_glass_pane = true
				versailles_planks = true
				whirlwind_planks = true
				large_diamond_glass_pane = true
				framed_planks = true
				square_glass = true
				vined_trapdoor = true
				barrel = true
				woven_glass = true
				detailed_planks = true
				woven_trapdoor = true
				cobweb_trapdoor = true
				gated_door = true
				supported_door = true
				barred_trapdoor = true
				line_bared_glass_pane = true
				horizontal_lined_glass_pane = true
				airy_trapdoor = true
				line_bared_glass = true
				slanted_planks = true
				barred_door = true
				suspicious_trapdoor = true
				herringbone_planks = true
				pressed_door = true
				planks_panel = true
				vertically_railed_planks = true
				bared_glass_pane = true
				diamond_bordered_glass_pane = true
				solid_trapdoor = true
				tiled_planks = true
				boarded_door = true
				dual_paneled_door = true
				square_glass_pane = true
				meshed_trapdoor = true
				thin_planks = true
				fancy_trapdoor = true
				paper_door = true
				warted_trapdoor = true
				basket_woven_planks = true
				enclosed_planks = true
				double_herringbone_planks = true
				crated_planks = true
				horizontal_lined_glass = true
				natural_planks = true
				classic_windowed_trapdoor = true
				brick_bond_planks = true
				wickered_planks = true
				bordered_glass_pane = true
				sliding_door = true
				heavy_trapdoor = true
				bordered_glass = true
				laced_planks = true
				boxed_planks = true
				reinforced_crate = true
				large_diamond_glass = true
				snowflake_glass_pane = true
				bricky_planks = true
				slotted_trapdoor = true
				shack_door = true
				polished_planks = true
				ornate_bared_glass_pane = true
				diagonal_planks = true
				wall_torch = true
				crate = true
				nailed_planks = true
				cornered_planks = true
				shifted_planks = true
				vertical_planks = true
				glass_door = true
				fortified_door = true
				paneled_door = true
				leafy_trapdoor = true
				snowflake_glass = true
				heavy_door = true
				pointless_trapdoor = true
				stacked_planks = true
				planks_shavings = true
				twisted_trapdoor = true
				diamond_planks = true
				woven_glass_pane = true
				windowed_trapdoor = true
				tile_windowed_door = true
				golden_barred_trapdoor = true

			[general.entries.wood_type.quark]
				vertical_planks = true
				ladder = true
				post = true
				trapped_chest = true
				chest = true
				hollow_log = true
				bookshelf = true
				stripped_post = true

			[general.entries.wood_type.twilightforest]
				banister = true
				hollow_log_climbable = true
				hollow_log_horizontal = true
				hollow_log_vertical = true

			[general.entries.wood_type.another_furniture]
				flower_box = true
				shutter = true
				drawer = true
				shelf = true
				bench = true
				table = true
				chair = true

			[general.entries.wood_type.decorative_blocks]
				seat = true
				palisade = true
				beam = true
				support = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.hearth_and_home]
				lattice = true
				sanded_wood = true
				parquet = true
				vertical_trim = true
				trim = true

			[general.entries.wood_type.twigs]
				table = true

			[general.entries.wood_type.backpacked]
				backpack_shelf = true

			[general.entries.wood_type.friendsandfoes]
				beehive = true

